spring:
  cloud:
    gateway:
      routes:
        - id: test_router
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test_router3333
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://renren-fast   #表示使用负载均衡服务，转发到renren-fast服务。
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  # 这个是重写路径。 具体的可以百度一下nacos路径重写
## 前端项目，发来的请求都带/api前缀,目前全部默认到renren-fast
